# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hila Peleg
tagline:          'A Jekyll theme'
description:      '@hilapeleg'
url:              http://hilapeleg.io
paginate:         5
baseurl: /www

author:
  name:           'Hila Peleg'
  url:            http://hilapeleg.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hilapeleg/www
