# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'A Jekyll theme'
description:      '@hilapeleg'
url:              http://lanyon.getpoole.com
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
